### ISSUE TITLE
Question about the future

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#10]
I would like to ask if you have abandoned this project. 

Thanks

**Comment by navjottomer** [comment]
Not abandoned but stalled till I get some more time to work on this again. In that meantime, I will happily entertain pull request.

**Comment by eurobank** [comment]
ok got it. Have you (or anyone else) used this code with a live site ?

**Comment by navjottomer** [comment]
Didn't use it on live site yet, but was waiting for proper testing and benchmarking before deployment on live site ( My installation already have modified osclass, so I don't need it so much on that website ). Due to not so much interest from the community, I stalled it further.

**Comment by eurobank** [comment]
Glad to hear that, since Osclass official project is dead (not sure if it is burried also).
