### ISSUE TITLE
Rewrite rules

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#103]
We can make faster  routes match with some small changes in rewrite class ..( work in progress )

**Comment by navjottomer** [comment]
Waiting for your pull request then.

**Comment by web-media** [comment]
one idea i'm thinking is splitting  front routes and admin routes . 
@navjottomer   @dev-101  @webmods-croatia   everybody else... what do you think ?

**Comment by webmods-croatia** [comment]
It could certainly speed things up, but break plugins. They could be updated easily tho.
