### ISSUE TITLE
[3.9 Master RC] PHP Warning:  join(): Invalid arguments passed 

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#117]
**Describe the bug**

This is from my debug log, apparently when i log as admin:

[10-Nov-2019 18:22:35 Europe/Madrid] PHP Warning:  join(): Invalid arguments passed in /home/oc-admin/controller/settings/main.php on line 52

Not sure if it comes from 3.9 core or from some plugins i have installed and tested.

I have disabled **ALL** plugin and wait to see if this continues.

**Comment by webmods-croatia** [comment]
@eurobank Seems like a bug with old auto-updating. I will fix immediately.

**Comment by navjottomer** [comment]
https://github.com/navjottomer/Osclass/commit/35d6dccf89b414c048c4b40b659beccc04f253ef
