### ISSUE TITLE
User::newInstance()->findFieldByPrimaryKey('s_name')

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#130]
A function like the one in the title: _User::newInstance()->findFieldByPrimaryKey('s_name')_ should be added to all models. Plugins and themes waste a lot of resources with _User::newInstance()->findByPrimaryKey($user)_ just to get email or name.

**Comment by navjottomer** [comment]
Your method name confused me, "Find field by primary key". Do you mean, "Find by field and primary key"? Above method argument is a field name( 's_name' ), where is primary key argument?
Sorry, It doesn't make any sense to me.

**Comment by webmods-croatia** [comment]
@navjottomer My bad. I meant findFieldByPrimaryKey('s_name', $id). So we can select only one field where the primary key is $id.

The function would look like this:

```php
        public function findFieldByPrimaryKey($field, $id)
        {
            $this->dao->select($field);
            $this->dao->from($this->getTableName());
            $this->dao->where($this->getPrimaryKey(), $id);
            $result = $this->dao->get();
            if($result == false) {
                return array();
            }
            if( $result->numRows() != 1 ) {
                return array();
            }
            return $result->row()
        }
```

**Comment by navjottomer** [comment]
I think performance shouldn't be a reason for such a method as both will perform the same as in most of the situations.
But this can be another good basic method to access the object to make developers life a bit easier.
Anyway, before any such change, we should focus ourself to primary issues. A workaround is pretty easy to do, a lazy developer shouldn't be our priority for now.
