### ISSUE TITLE
User Selected Duration for each Ad Posted

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#131]
Back in the old "forum" days, i asked and i was told that Ad Duration (per ad)  feature IS actually implemented but not "used".

Not sure what exactly that means, but it would be nice some dev to research it.

**Comment by eurobank** [comment]
Now that i read again the (saved) reply, they say Osclass has implemented it and it is for the themes to use it.

Still if someone could as some point check it out.....

**Comment by navjottomer** [comment]
I think I can safely close this as it is not an issue itself with osclass.
