### ISSUE TITLE
Plugin Compatibilty Problem

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#132]
Sorry to open an issue and probably not related to 3.9 (not sure). But i can't update to 3.9 unless i find the cause and a solution,

This is my crash, happening within Spam plugin. 

> [17-Nov-2019 12:05:11 Europe/Madrid] PHP Fatal error:  Uncaught phpmailerException: Invalid address:  (addAnAddress to):  in /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php:881

How can i address this ?

**Comment by navjottomer** [comment]
I am sure you know about support forum. You should consider that for any support related issue.
BTW look of this error, it is easy to say that an invalid address is given to PHP mailer library.

**Comment by eurobank** [comment]
ok. btw this is not an invalid address since there is no problem before 3.9.

**Comment by navjottomer** [comment]
We have used a new version of PHP mailer library, maybe that's why? Plugin will need to be checked for cause of this issue.
