### ISSUE TITLE
WebThemes::newInstance()->loadThemeInfo

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#137]
Theme info is parsed multiple times during same request , never stored .  
```php 
 $s_info = file_get_contents($path);
            $info   = array();
 if($info['name']!='') {
                return $info;
            }
```
 also old code info  seems a lot faster   than  9 times preg_match  in actual method . 
```php 
 // OLD CODE INFO
            require_once $path;
            $fxName = $theme . '_theme_info';
            if (!function_exists($fxName)) {
                return false;
            }
            $result = call_user_func($fxName);
            $result['int_name'] = $theme;

            return $result;
```
i think that we should prioritize old code info with some defaults values if not present and than  doing the preg match .

**Comment by web-media** [comment]
pull request #139

**Comment by web-media** [comment]
This class require some additional work to be done .

**Comment by navjottomer** [comment]
Please add more information in future issues title for some context.
