### ISSUE TITLE
Installer not working - HTML Purifier missing

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#14]
Error when using installer:

Fatal error: require_once(): Failed opening required '/oc-includes/htmlpurifier/HTMLPurifier.auto.php' (include_path='.:/usr/share/pear:/usr/share/php') in /oc-includes/osclass/install-functions.php on line 19

By the way, I forked this repository and I completely removed all ties with Osclass Market. Once this is fixed I will test and make a pull request.

**Comment by webmods-croatia** [comment]
Same error in Params.php. Have you wanted to remove HTML Purifier completely or it's missing unintentionally?

**Comment by navjottomer** [comment]
Nope, they are moved to composer vendor directory. I still need to fix this issue.

**Comment by webmods-croatia** [comment]
Okay, thank you.

**Comment by navjottomer** [comment]
Fixed Now (At least working on my system), try new release or update your repo.
