### ISSUE TITLE
Params purify

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#140]
self::$_config getting Rewritten on each  purify action with the same  default config

**Comment by web-media** [comment]
Also to allow default purifier config to be extended 
http://htmlpurifier.org/live/configdoc/plain.html

**Comment by navjottomer** [comment]
https://github.com/navjottomer/Osclass/commit/1ca7ee237986abe966d76cba34a45ea57b291aac
https://github.com/navjottomer/Osclass/commit/00d865ba353914322ce742124a54ee50b835497d
https://github.com/navjottomer/Osclass/commit/68074c045cde70950748214e50a293f23f21c0f3
