### ISSUE TITLE
Params :: getParam

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#142]
we also need  additional  simpler and faster methods to  clean the variables  than Purify

booleans,integers,emails ... etc 
```php
return preg_replace('/[^[:alpha:]]/', '', self::$_request[$param]);
``` 
```php
return (int)self::$_request[$param];
``` 
```php
 return preg_replace('/[^[:alnum:]]/', '', self::$_request[$param]);
``` 
```php
  $param = preg_replace('/[^-\.@_\-,a-z0-9]/', '', $param);
```

**Comment by navjottomer** [comment]
Better if we remove all sanitizing, formatting, cleaning to separate class. 
@dev-101 what you say?

**Comment by dev-101** [comment]
Using regex to sanitize html is bad idea. I wouldn't change this at all.

**Comment by navjottomer** [comment]
@dev-101 Sorry I didn't make myself clear, I was not talking about @web-media ideas but moving all formatting related code to separate class, methods in that class can be used in other classes. Currently, there is lots of duplicate code hanging around in different files.

**Comment by dev-101** [comment]
Ah, ok... that's fine.

**Comment by navjottomer** [comment]
BTW what I understand from @web-media 's comment is that he wants to add additional methods (for simple use case) without removing existing HTMLPurifier methods. 
But I am not sure that is even needed right now. This can be a part of the new supposed formatting class.

**Comment by web-media** [comment]
filter_var do just fine for many cms , opencart , codeigniter , etc 
https://www.php.net/manual/en/filter.filters.sanitize.php
```php
filter_var ( $text, FILTER_SANITIZE_STRING);
```
```php
$quantity = '10a00.434';

$quantity = filter_var($quantity, FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);

echo $quantity;
```
some work here https://github.com/web-media/validation/blob/master/OscFilter.php

**Comment by web-media** [comment]
https://github.com/web-media/validation
