### ISSUE TITLE
All Static Pages are Noindex, Nofollow ....

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#143]
I see the old bug of 3.8 still here.

All static pages created by Osclass are as follows:

```
<meta name="generator" content="Osclass 3.9.0" /><meta name="robots" content="noindex, nofollow, noarchive" />
<meta name="googlebot" content="noindex, nofollow, noarchive" />
```

Personally i see no reason why static pages should be excluded from seach engines indexing.

**Comment by web-media** [comment]
we need  an option  to admin back end to choose from follow - no follow

**Comment by eurobank** [comment]
@web-media what pages created by the admin could be tagged as nofollow and why ? 

Usually we create "about", "privacy" etc. Why exclude them from index ?

**Comment by web-media** [comment]
Thank you pages , custom search pages ...

**Comment by webmods-croatia** [comment]
> we need an option to admin back end to choose from follow - no follow

I agree.

**Comment by navjottomer** [comment]
Okay, I checked and found that osclass itself doesn't control this. It's up to theme developer to implement these things.
And because this issue is not related to osclass itself, I am closing this now.
