### ISSUE TITLE
Blocked users are not blocked when logged in

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#152]
If you block a user while he is logged in and abusing the Contact service with spam (for example), the user is NOT immediately blocked. 

And can continue to abuse the Contact service until logged off.

**Comment by webmods-croatia** [comment]
Any more clever ideas than checking if the user blocked every time a page is loaded?

**Comment by eurobank** [comment]
Maybe only when a Comment/Contact/New Ad is posted?

**Comment by navjottomer** [comment]
@webmods-croatia  if the cookie doesn't validate, he may no longer be logged in.

**Comment by eurobank** [comment]
@navjottomer 

Correct!!!

Because i tested it and if the user doesn't log off and just leaves the browser, he can continue when he browses again!!!!

So it is cookie related.

**Comment by navjottomer** [comment]
There is a check for the blocked user while checking the user login session. Blocking user is properly invalidating user session or I have missed something. 
@eurobank can you explain step by step process to reproduce this issue.

**Comment by eurobank** [comment]
@navjottomer 

What happens is:

1. There is a new spammer registered and logged in.
2. He is using the Contact Publisher to spam whatever ads he can
3. When i'm aware of that (after he spammed a few) i BLOCK him within the users admin.
4. But he can continue to spam until i delete him (but he registers back)

**Comment by web-media** [comment]
you should ban email in  Users ->Ban rules
and the banned User will  receive a  notice 

![banUser](https://user-images.githubusercontent.com/5124319/70003414-54fc7c00-1563-11ea-8c56-619ec4d68ab2.PNG)

```php
 case 'contact_post':
                    osc_csrf_check();
                    if( osc_reg_user_can_contact() && !osc_is_web_user_logged_in() ){
                        osc_add_flash_warning_message( _m("You can't contact the seller, only registered users can") );
                        $this->redirectTo( osc_base_url(true) );
                    }

                    $item = $this->itemManager->findByPrimaryKey( Params::getParam('id') );
                    $this->_exportVariableToView('item', $item);
                    if ((osc_recaptcha_private_key() != '')) {
                        if(!osc_check_recaptcha()) {
                            osc_add_flash_error_message( _m('The Recaptcha code is wrong') );
                            Session::newInstance()->_setForm("yourEmail",   Params::getParam('yourEmail'));
                            Session::newInstance()->_setForm("yourName",    Params::getParam('yourName'));
                            Session::newInstance()->_setForm("phoneNumber", Params::getParam('phoneNumber'));
                            Session::newInstance()->_setForm("message_body",Params::getParam('message'));
                            $this->redirectTo( osc_item_url( ) );
                            return false; // BREAK THE PROCESS, THE RECAPTCHA IS WRONG
                        }
                    }

                    $banned = osc_is_banned(Params::getParam('yourEmail'));
                    if($banned==1) {
                        osc_add_flash_error_message( _m('Your current email is not allowed'));
                        $this->redirectTo(osc_item_url());
                    } else if($banned==2) {
                        osc_add_flash_error_message( _m('Your current IP is not allowed'));
                        $this->redirectTo(osc_item_url());
                    }
```

**Comment by web-media** [comment]
we should  do some 
```php
time() - (int)Session::newInstance()->_get('last_contact_time')) < osc_item_contact_wait_time() ;
// Track spam delay: Session
                    Session::newInstance()->_set('last_contact_time', time());
                    // Track spam delay: Cookie
                    Cookie::newInstance()->set_expires(osc_time_cookie());
                    Cookie::newInstance()->push('last_contact_time', time());
                    Cookie::newInstance()->set();

```

**Comment by eurobank** [comment]
If i ban the user, if he has also ads posted, they remain posted. Blocking users disables the ads also. Same for IP ban. 

Also ban users for that reason will  grow a huge list of ips and emails. 

BUT i will try to test your suggestion, if it works. It is not easy to test, i need to work with two browsers etc etc.

I will update.

**Comment by eurobank** [comment]
Spend a few hours, trying to replicate on my live system the problem i reported (stock 3.8). 

And i failed to be honest. When i blocked a user, the user was sent to the login page, no matter what he was doing.

So i'm not sure how spammers continue for hours to use the contact seller page after beeing blocked.

**Comment by navjottomer** [comment]
Closing this now, I am not able to replicate this issue.
