### ISSUE TITLE
[autoload branch] Some Crash with 3rd party theme

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#164]
I'm posting this because i think some compatibility or else broke with todays autoload branch.

And since Osclass Wizards is the most used theme .... you figure out what i mean ....

> 
> [02-Dec-2019 14:16:53 Europe/Madrid] PHP Fatal error:  Uncaught Error: Call to undefined function getConnection() in /home/oc-content/themes/osclasswizards/admin/category-icons.php:10
> Stack trace:
> #0 /home/oc-content/themes/osclasswizards/admin/settings.php(125): include()
> #1 /home/oc-admin/themes/modern/appearance/view.php(47): require_once('/home/...')
> #2 /home/oc-includes/osclass/helpers/hDefines.php(221): require('/home/...')
> #3 /home/oc-admin/appearance.php(238): osc_current_admin_theme_path('/home/...')
> #4 /home/oc-admin/appearance.php(211): CAdminAppearance->doView('appearance/view...')
> #5 /home/oc-admin/index.php(113): CAdminAppearance->doModel()
> #6 {main}
>   thrown in /home/oc-content/themes/osclasswizards/admin/category-icons.php on line 10
>

**Comment by web-media** [comment]
That  variable  is not used in that file and in that theme either .
```php
$conn = getConnection(); 
```
you could remove that line .
another example for another theme  flatter 
```php
function get_city($country_id) {
    $conn = getConnection();
    $db_prefix = DB_TABLE_PREFIX;
    $city = $conn->osc_dbFetchResults("SELECT pk_i_id, s_name FROM {$db_prefix}t_city WHERE fk_c_country_code='{$country_id}' ORDER BY s_name ASC");
    echo json_encode($city);
} 

```
theme  and plugin developers should not use this old legacy code. 
First :  is not safe. $country_id is not escaped properly .
Second :  This is old code from 10 years ago  osclass version 1.0.0 .
Third : They should invest some time and create proper model class and do not copy paste old code

**Comment by eurobank** [comment]
@web-media Thanks, that stopped the error.

Doing a search in all my Osclass folder, i found several plugins using that. I wil keep that in mind.

**Comment by web-media** [comment]
run like hell  from this kind of plugins . and developers .  :)
