### ISSUE TITLE
Variadic, variable functions in plugin class

### ISSUE THREAD

**Issue by navjottomer** [navjottomer/Osclass#166]
https://github.com/navjottomer/Osclass/commit/b29e88b66e2f0d87667dbe56b537ed9956a000a5
I have changed current hook implementation to new functions in the recent commit. I have tested it and new changes seem stable but need feedback.

@web-media @dev-101 @webmods-croatia ??

**Comment by webmods-croatia** [comment]
@navjottomer I will test with my plugins.

**Comment by webmods-croatia** [comment]
I tested User Custom Fields, Profile Picture and Video Embed.
All worked fine.

They use these hooks and filters:
user_add_flash_error
user_edit_flash_error
user_form
pre_item_post
pre_item_add_error
pre_item_edit_error
posted_item
edited_item
item_form
item_edit
delete_item
item_detail
init_admin
admin_footer
init
footer
pre_user_post
user_register_completed
user_edit_completed
user_register_form
user_profile_form
delete_user

**Comment by navjottomer** [comment]
@webmods-croatia thanks.

**Comment by web-media** [comment]
cannot access search pages
http://localhost/autoload/index.php?page=search&sCategory=1
The page isn’t redirecting properly , there  is a loop redirect
![loop](https://user-images.githubusercontent.com/5124319/70366354-06b6e800-1897-11ea-8d8c-451fac6c16b7.PNG) .

**Comment by navjottomer** [comment]
@web-media Not related to hooks, but fixed it here 5740c08f3a32084d0d3262700ae77b61e57a9525

**Comment by navjottomer** [comment]
I think this is safe, closing this down for now.
