### ISSUE TITLE
 contact controller osc_contact_attachment  should be optional 

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#167]
**Describe the bug**
not all themes implement contact attachment on contact page.
osc_contact_attachment must be optional

**To Reproduce**
1. enable Allow people to attach a file to the contact form  on admin general settings form
2. go to contact page
3. send message

**Expected behavior**
if  Params::getFiles('attachment') do not exist , do not   show osc_add_flash_error_message( _m('The file you tried to upload does not have a valid extension') );
                                        
 osclass version is 390 
![contact](https://user-images.githubusercontent.com/5124319/70328469-62eb1f00-1839-11ea-9bc3-d219eb16aac5.PNG)

**Comment by navjottomer** [comment]
Fixed https://github.com/navjottomer/Osclass/commit/e8e4a90ed6ea4e912f510024656fdbf8674ec8df
