### ISSUE TITLE
3.9.0  master cannot install 

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#169]
3.9.0  does not install  on live host .. i'll try autload branch
Notice: Use of undefined constant WEB_PATH - assumed 'WEB_PATH' in /oc-includes/osclass/default-constants.php on line 40

Warning: Class 'ImageProcessing' not found in /home3/oc-includes/osclass/compatibility.php on line 22

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home3/oc-includes/osclass/default-constants.php:40) in /home3/oc-includes/osclass/core/Session.php on line 96

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home3/oc-includes/osclass/default-constants.php:40) in /home3/oc-includes/osclass/core/Session.php on line 62

Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /home3//oc-includes/osclass/core/Session.php on line 62

Warning: session_start(): Failed to read session data: files (path: /tmp) in /home3/oc-includes/osclass/core/Session.php on line 62

Warning: session_regenerate_id(): Cannot regenerate session id - session is not active in /home3/oc-includes/osclass/core/Session.php on line 63

Warning: Cannot modify header information - headers already sent by (output started at /home3/oc-includes/osclass/default-constants.php:40) in /home3/oc-includes/osclass/install.php on line 103

**Comment by navjottomer** [comment]
@web-media Strange no one has this issue at the time of release and worked fine for me too.

**Comment by web-media** [comment]
must be something with the chars in  password i had a abc_>hhdnc . once i've changed  user password i 've succed

**Comment by web-media** [comment]
also wo't let me  put admin name  like abc_admin

**Comment by navjottomer** [comment]
Tested it on develop branch, installation working fine with above password but the username is no go due to the osclass validation js.

**Comment by web-media** [comment]
then we close the issue  .! 
 i'll test again  next week for 2 clients

**Comment by navjottomer** [comment]
Ok, reopen it if you found any issue then.
