### ISSUE TITLE
Array to string conversion Notice

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#17]
[09-Aug-2019 15:43:20 Europe/Madrid] PHP Notice:  Array to string conversion in /home/oc-includes/osclass/helpers/hSanitize.php on line 183

beta 2.

**Comment by dimalif** [comment]
I see the same report as mine, in a closed issue. You replied that it has to do with Bender.

Still, Bender is the default theme, so it is a problem i think. Or you think this is something that should be taken care separately and how ?

Since i never used Bender, i will test to see if this error exist also in the official 3.8 and update here.

**Comment by dimalif** [comment]
Ok, this doesn't happen with bender and stock 3.8 version.

**Comment by navjottomer** [comment]
Related to #19 , fixed it seems

**Comment by dimalif** [comment]
Yes, both problems fixed.
