### ISSUE TITLE
Error in the information area

### ISSUE THREAD

**Issue by csasua** [navjottomer/Osclass#170]
Hi guys, the new update of osclass 3.9 presents me with an error in the information area, this page shows all the options such as privacy policy, terms and conditions, etc., but when you see one of them the menus do not make the change and all remain in the name of the open menu

https://prnt.sc/q8feet

https://prnt.sc/q8ffb1

**Comment by eurobank** [comment]
Theme?

**Comment by csasua** [comment]
Hi,
it happens to me with all the issues, I made new installation and it
continues
best regards
Atte.
Christian A. Saravia Suárez
Santiago - Chile

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/12/19
16:46:26

**Comment by csasua** [comment]
it happens to me with all the themes, I made new installation and it
continues
best regards
Atte.
Christian A. Saravia Suárez
cel. 9 7218 9422
Santiago - Chile

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/12/19
16:47:39

**Comment by eurobank** [comment]
I can't replicate it and maybe your descripiton doesn't help much.

**Comment by csasua** [comment]
In home looks good the links of: 
Terms 
Privacy
Security
Help

but once you enter them (in anyone) you only see the one you entered

It happens to me with all the themes that I have tried, the image is of the bender the engine is the last osclass downloaded from github

osclass-master : 3.9.0 of 14-11-2019
php 7.2
theme: bender 3.2.0
clean installation (no upgrade)

this also happens in the mobile phone

![normal](https://user-images.githubusercontent.com/58701894/70479776-d81a5680-1abc-11ea-9e1c-4632876adff0.png)
![error](https://user-images.githubusercontent.com/58701894/70479785-de103780-1abc-11ea-9d94-4340eff1d348.png)

**Comment by navjottomer** [comment]
@csasua I hope this will fix this issue, It was an old bug in osclass  due to improper handling of page loops https://github.com/navjottomer/Osclass/commit/d7a9ea61d197f9048e4858f1f2c406a0e82987b2
