### ISSUE TITLE
osc_static_page_title() not working properly in menus when on a static page.

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#174]
![Page3](https://user-images.githubusercontent.com/53878055/71549701-29ce4680-29c2-11ea-937a-2c85fb65b6c6.png)
osc_static_page_title() not working properly in menus when on a static page.

https://forums.osclasscommunity.com/general-discussion/custom-pages-on-footer-ver3-9-bug

> 3.9 version has strange bug.
> Links to custom pages are visible on the footer.
> Lets say there are three custom pages with links Page1, Page2, Page3
> Those links are correctly displayed on footer only on home page.
> If you go to any of those custom pages, other links are changed to the same url and name.
> 
> So if you go to custom page Page1, all custom links on footer will show as Page1, PAge1, Page1
> If you go to custom page Page2, all custom link on footer will show as Page2, Page2, Page2
> 
> Checked on a fresh installation. Version 3.8 is OK.

**Comment by navjottomer** [comment]
The issue has been already identified and fixed int latest dev version. It is an old issue from the previous generation of osclass version. #170

**Comment by webmods-croatia** [comment]
Sorry, title of that issue wasn't very precise so I didn't see it.

**Comment by navjottomer** [comment]
No worry.
