### ISSUE TITLE
add single language will install all languages

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#181]
go to Admin/languages add language, upload zip file
also 
```php
[06-Jan-2020 09:49:37 Europe/Madrid] PHP Warning:  mkdir(): File exists in N:\a\htdocs\develop\oc-includes\osclass\utils.php on line 1276
```
![languages](https://user-images.githubusercontent.com/5124319/71807196-fd25c900-306a-11ea-93e0-94df73d3e4e0.PNG)

**Comment by webmods-croatia** [comment]
Currently, all languages are bundled, which will be changed in the next version (when I get some time) as we will make languages downloadable like locations.

**Comment by navjottomer** [comment]
as already explained by @webmods-croatia. closing it now.
