### ISSUE TITLE
Question on Upgrading

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#188]
3.9 (from what a read) has several files re-arranging, moved to other folders etc etc.

Going from 3.8 to 3.9, what becomes of the old files? They remain unused? It that safe?

**Comment by webmods-croatia** [comment]
They remain unused, yes. What I would do if I was upgrading is to delete whole oc-includes and then upload new one, instead of just replacing the files (and keeping the unused old ones).

**Comment by dimalif** [comment]
Ok, if that safe to leave them?

I mean, i already did that but others are not aware.

**Comment by navjottomer** [comment]
We have a support forum for these type of discussion please use that instead of this.

**Comment by dimalif** [comment]
Leaving behind a huge ammount of folders and files is not good. Who knows those php files what kind of open holes have or might have in the future.

The upgrade script should take care of that, as it happens with other popular scripts.
