### ISSUE TITLE
user-items.php syntax error for toggle view list/gallery

### ISSUE THREAD

**Issue by ZeroFossilFuel** [navjottomer/Osclass#189]
When a user is logged into their dashboard and viewing their own active listings, attempting to toggle between list and gallery view produces a blank page using the default theme prior to adding any new themes, Bender, Modern and many others.

**To Reproduce**
1. Create a user account, NOT an admin account.
2. Log in and create 2 or more listings.
3. Go to 'userdomain.com/index.php?page=user&action=items'
4. Click on list/gallery view button.
5. See error

**Expected behavior**
View should toggle between list and gallery

**Screenshots**

**Additional context**
The error is found in
**~/oc-includes/osclass/gui/user-items.php** lines 47 & 48. If Bender 3.2.0 theme has been manually installed, the bug also appears in **~/oc-content/themes/bender/user-items.php** lines 47 & 48. This same error has also propagated to many other themes. Theme-Modern has been verified to also have this same bug.

Wrong

>                 <a href="<?php echo osc_user_list_items_url(); ?>?ShowAs=list" class="list-button" data-class-toggle="listing-grid" data-destination="#listing-card-list"><span>Lista</span></a>
>                 <a href="<?php echo osc_user_list_items_url(); ?>?ShowAs=gallery" class="grid-button" data-class-toggle="listing-grid" data-destination="#listing-card-list"><span>Grid</span></a>

Correct

>                 <a href="<?php echo osc_user_list_items_url(); ?>&ShowAs=list" class="list-button" data-class-toggle="listing-grid" data-destination="#listing-card-list"><span>Lista</span></a>
>                 <a href="<?php echo osc_user_list_items_url(); ?>&ShowAs=gallery" class="grid-button" data-class-toggle="listing-grid" data-destination="#listing-card-list"><span>Grid</span></a>

**Comment by xiris** [comment]
Discussion: https://osclass.discourse.group/t/user-listing-admin-view-blank-when-attempting-to-toggle-list-gallery-bender-3-2-0/100

**Comment by ZeroFossilFuel** [comment]
This bug is embedded in the core product and propagates to other themes because of it.
**~/oc-includes/osclass/gui/user-items.php**
