### ISSUE TITLE
PHP Warning:  join(): Invalid arguments passed

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#193]
**Describe the bug**

Errors in debug.log

**To Reproduce**

I can't tell.

I run PHP 7.3 and Osclass 3.9. 

`[21-Jan-2020 16:02:51 Europe/London] PHP Warning:  join(): Invalid arguments passed in /home/oc-admin/controller/settings/main.php on line 52`

**Comment by webmods-croatia** [comment]
Fixed in develop branch.

**Comment by eurobank** [comment]
This seems to be a PHP 7.3, with PHP 7.2.x shows no warnings.

**Comment by webmods-croatia** [comment]
With which branch are you testing?

**Comment by eurobank** [comment]
Osclass 3.9 release. No testing anything, a live site.

**Comment by webmods-croatia** [comment]
Ok, it's fixed as I said. Will be included in the new version.
