### ISSUE TITLE
 PHP Fatal error:  Uncaught phpmailerException: Invalid address

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#194]
**Describe the bug**

In debug.log

**To Reproduce**

I have no idea

I run PHP 7.3 and Osclass 3.9

```
[24-Jan-2020 12:32:37 Europe/London] PHP Fatal error:  Uncaught phpmailerException: Invalid address:  (addAnAddress Reply-To): ol.eg.ser.g.l.i.s.@gmail.com in /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php:931
Stack trace:
#0 /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php(902): PHPMailer->addAnAddress('Reply-To', 'ol.eg.ser.g.l.i...', '')
#1 /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php(856): PHPMailer->addOrEnqueueAnAddress('Reply-To', 'ol.eg.ser.g.l.i...', '')
#2 /home/oc-includes/osclass/utils.php(496): PHPMailer->addReplyTo('ol.eg.ser.g.l.i...')
#3 /home/oc-includes/osclass/controller/contact.php(156): osc_sendMail(Array)
#4 /home/index.php(132): CWebContact->doModel()
#5 {main}
  thrown in /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php on line 931


```

**Comment by webmods-croatia** [comment]
@eurobank Seems like some spammer tried to contact you and they put an invalid formatted mail that "broke" PHPMailer.

"ol.eg.ser.g.l.i.s.@gmail.com"

I think this can be closed. Mail validation should be done on client -> theme side.

**Comment by eurobank** [comment]
Sure, still i never have seen that in the past (6 years or so).

**Comment by DonDominios** [comment]
Hello @eurobank I am having the same problem, were you able to solve it or do you know how to solve the problem?

**Comment by eurobank** [comment]
@DonDominios Hi, actually didn't. And i don't care since it seems rare. There are much more severe bugs right now, for example ads expirations...
