### ISSUE TITLE
PHP Notice:  Array to string conversion

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#2]
PHP 7.0.26, Bender, no plugins.

[09-Dec-2017 20:30:15 Europe/Madrid] PHP Notice:  Array to string conversion in /home/oc-includes/osclass/helpers/hSanitize.php on line 183

**Comment by navjottomer** [comment]
I will keep it open till we are not able to reproduce this error. Most likely related to Bender theme, if it is than it should be closed.

**Comment by eurobank** [comment]
Well closing issues because you can't replicate, will cause a havoc later. Anyway, feel free to do whatever you want.

**Comment by navjottomer** [comment]
If it is related to osclass than it needed to be open, but if related to bender theme than it should be closed. What do you say?

**Comment by eurobank** [comment]
Me ? I have no idea. BUT that problem came with your updates. Wasn't there before. 

But you are the programmer and the boss. Do what it is best !
