### ISSUE TITLE
New forum? - not an real issue, sorry :)

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#24]
Hi!

I talked with @navjottomer about a new forum where we can discuss freely as a lot of recent posts got removed from Osclass Forums. He said he likes the idea, so here I am...

I bought a domain, loveosclass.com, installed MyBB, played with the design for a few hours (to make it responsive!) and boom - we have LoveOsclass forums.
I am inviting you all to join and discuss Osclass. The site will have some exclusive content as well. Such as documentation, tutorials, free plugins and maybe even themes.

The main reason, however, is to talk about future of Osclass, post links to backups (which get removed from Osclass forums), etc.

Please don't take this post as something rude or as advertising. I don't earn any money from the forum. It contains the donate link and if I ever get a donation it will help with hosting.

**Comment by navjottomer** [comment]
Please, do not post anything which is not related to the development of this repo. README.md will be updated if there is any new info.
