### ISSUE TITLE
A close look at Internal CRON not running 

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#26]
For me internal CRON never run at all. Not sure why, two hosting companies, same problem. 

While in the same plan, Wordpress sites  CRON runs just fine.

Maybe now this problem could be examined and fixed ?

**Comment by webmods-croatia** [comment]
Cron has been buggy from the start... I never used Osclass cron functions for my mods because of those issues.

**Comment by dev-101** [comment]
There aren't any issues with cron.
Any issue with cron is probably server environment related.
Cron is very basic, really.

**Comment by webmods-croatia** [comment]
Some issues with cron functions were reported on forums. Hmm...

čet, 15. kol 2019. 17:44 Darko <notifications@github.com> je napisao:

**Comment by dimalif** [comment]
There are issues with CRON. Definitely.

**Comment by dev-101** [comment]
Do you use any protection script or plugin that may block cron triggers? Also, do you use external server cron trigger or async cron?

**Comment by dimalif** [comment]
Same plan 2 Osclass and two Wordpress. Osclass cron never runs with Internal CRON. No errors about CRON anywhere.  I use now CRON from my Cpanel for Osclass. 

On the other hand Wordpress CRONS run just fine,

**Comment by webmods-croatia** [comment]
Same error that @dimalif mentioned. You need to add cron to cPanel or VestaCP or whatever for it to work.

**Comment by dev-101** [comment]
Some WAF applications can prevent cron triggers.
Anyway, for internal crons to run you need visitors, also, it is easy to debug cron (not) triggering, and also track values in cron table (database). Then, you can see why it is not happening.

However, it always a better idea to define external cron, because you have exact control when it runs. I know, that does not solve your issues, but you need to debug it to understand why it does not run in the first place. @webmods-croatia you should be able to do it, at least, because I cannot reproduce this in my systems.

**Comment by dev-101** [comment]
You can also modify cron.php to run every minute (instead of hour), in order to debug it faster.

**Comment by webmods-croatia** [comment]
I'll see when I have time. I use external (cPanel) cron for years now
without problems, but I know that I had issues with internal cron before.
Maybe it really was a lack of visitors.

čet, 15. kol 2019. 23:34 Darko <notifications@github.com> je napisao:

**Comment by dimalif** [comment]
No lack of visitors for me. A production site with around 5000 visitors per day.

**Comment by dimalif** [comment]
If anybody want to put some debug code here for cron, i would be glad to test.

**Comment by webmods-croatia** [comment]
> You can also modify cron.php to run every minute (instead of hour), in order to debug it faster.

**Comment by dimalif** [comment]
God bless you Navjot, the CRON issue is fixed !!!

Just tested it.

**Comment by neludd** [comment]
hello me on the site the changes in the utils.php tab do not work to run cron to the minute not to the hour. After I modified the utils file the error is the white page
