### ISSUE TITLE
PHP Notice:  Plugin osclasswizards is missing the index.php file

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#3]
Switching from bender to Free OsclassWizards theme, i see this:

[09-Dec-2017 20:36:37 Europe/Madrid] PHP Notice:  Plugin osclasswizards is missing the index.php file /home/oc-content/plugins/osclasswizards/index.php in /home/oc-includes/osclass/classes/Plugins.php on line 124

The Osclasswizards is untouched and i REinstalled it from Market. And Index.php is not missing, it is there.

PHP 7.0.26.

Also all my test are on a SUBDOMAIN, could that be a problem ?

**Comment by eurobank** [comment]
Switching to an other free theme, Azzuro, i don't see that problem. So it must be OsclassWizards specific.

**Comment by eurobank** [comment]
**On a clean/virgin installation and db**, i don't see that error.

**Comment by navjottomer** [comment]
I think we should close this issue than.
