### ISSUE TITLE
Question about untie from market

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#31]
Excuse me if my thought is stupid. 

I see in Wordpress that MANY core functions are nulled/disabled/changed with a PLUGIN. Even Gutenberg. (Auto) Updates also. 

I see that same functionality is available in Osclass with some plugins (SEO for example).

So wouldn't be possible to NULL Osclass Market with a plugin ?

**Comment by navjottomer** [comment]
It can be done, but If it needs to be installed on every installation than isn't better to include it in the core. Still, the current goal is to only remove reliance on osclass market. So we wouldn't need to reinvent the wheel when we add an open-source market. It is still not certain maybe the community will use some else plugin to use as a market alternative. We'll make this decision in future as this not a concern right now.
