### ISSUE TITLE
Question about plugins/themes that broke with these changes

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#33]
I would like to ask what will happen with some plugins or themes that broke with these changes.

Especially if the plugins/themes are abandoned by their developer. Post here the findings ? Or not.

**Comment by navjottomer** [comment]
Firstly, I am removing or updating parts only which are already deprecated or not needed anymore. But I can not guarantee that it will not break compatibility of any plugins/themes. But compatibility issues can be easily fixed. I will open a forum for such kind of discussion if needed.

**Comment by dimalif** [comment]
got it.
