### ISSUE TITLE
phpmailer for develop branch

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#34]
**If this is caused by the plugin mentioned in the log (spamprotection), just forget it.** I'm posting this because it didn't happened with the beta2.

[17-Aug-2019 19:28:29 Europe/Madrid] PHP Fatal error:  Uncaught phpmailerException: Invalid address:  (addAnAddress to):  in /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php:881
Stack trace:
#0 /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php(821): PHPMailer->addOrEnqueueAnAddress('to', '', '')
#1 /home/oc-includes/osclass/utils.php(465): PHPMailer->addAddress('', NULL)
#2 /home/oc-content/plugins/spamprotection/classes/class.spamprotection.php(1679): osc_sendMail(Array)
#3 /home/oc-content/plugins/spamprotection/admin/plugin.php(194): spam_prot->_testMail('', '', '')
#4 /home/oc-content/plugins/spamprotection/admin/main.php(166): include_once('/home/...')
#5 /home/oc-admin/themes/modern/plugins/view.php(34): require_once('/home/...')
#6 /home/oc-includes/osclass/helpers/hDefine in /home/oc-includes/vendor/phpmailer/phpmailer/class.phpmailer.php on line 881

**Comment by navjottomer** [comment]
I couldn't reproduce it in osclass.

**Comment by dev-101** [comment]
This issue "referenced" other issues because of wrong code formatting in original post and #
but they are all unrelated.
