### ISSUE TITLE
"Make primary image" when posting item is integrated but hidden.

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#35]
Osclass actually haves "Make primary image" button when posting an item, but it's content is empty. There is no text.

In [oc-includes/osclass/frm/Item.form.class.php:1676](https://github.com/navjottomer/Osclass/blob/master/oc-includes/osclass/frm/Item.form.class.php)

replace

```js
$(li).append('<div class="primary_image"><a title="<?php echo osc_esc_js(osc_esc_html(__('Make primary image'))); ?>"></a></div>')
```

with

```js
$(li).append('<div class="primary_image"><a title="<?php echo osc_esc_js(osc_esc_html(__('Make primary image'))); ?>"><?php echo osc_esc_js(osc_esc_html(__("Make primary image"))); ?></a></div>');
```

to make the button appear. Tested and working.

**NOTE:** This was found out by @marius-ciclistu on Osclass Community forums.

**Comment by dev-101** [comment]
Most likely, this was unintentional bug.
