### ISSUE TITLE
Emails Links Format

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#37]
Maybe this could be (properly) fixed ?

https://github.com/osclass/Osclass/issues/2189

This problem is for all emails sent from Osclass, not only for activating emails. Email send to admins also etc etc. 

While in Gmail the links are "understood" and linked, in other mail client do not. Still why not have them correctly formatted....

**Comment by eurobank** [comment]
I made a capture to be more clear about the problem. As you can see everything is hyperlinked BUT one url. The same happens in several email urls.

![emails_links](https://user-images.githubusercontent.com/4467158/63255186-de6e9380-c27d-11e9-9dac-be7ea69e7339.png)

**Comment by eurobank** [comment]
I think a fix is needed here:

function fn_email_admin_new_item

**Comment by navjottomer** [comment]
I think it would be better if you can make a pull request with those changes. It would surely save some time.

**Comment by eurobank** [comment]
I surely would, if i was a programmer and know about all this stuff.

**Comment by navjottomer** [comment]
No problem, you can still find those locations and other bugs. I'll keep this issue open.

**Comment by eurobank** [comment]
The same problem in "email_admin_new_item", checking the template for it in admin, i see "Url: {ITEM_URL}" used. What is the difference between

{ITEM_URL}
Listing url
&
{ITEM_LINK}
Listing list

because if i put there {ITEM_LINK} works fine as link. Maybe the problem are in the templates ?

**Comment by webmods-croatia** [comment]
Gmail automatically ads "a" tag to links making them clickable. Not a thing in other clients. I will check the templates.

**Comment by eurobank** [comment]
Yes Gmail does that. Still not everybody uses Gmail. And why half of the links are ok and the other half not ? I don't get it. Different developers ?

**Comment by webmods-croatia** [comment]
No idea, but I tried adding "a" tags in templates and it didn't work. Looking at oc-includes/osclass/emails.php, some mails really have them and some not.
I will create a pull request.

**Comment by eurobank** [comment]
@webmods-croatia Keep in mind that one was fixed:

https://github.com/navjottomer/Osclass/commit/3689b2376090d27347545ca3d83016bac0a1869a

**Comment by webmods-croatia** [comment]
"function fn_email_admin_new_item" seems okay, it isn't working good?

**Comment by eurobank** [comment]
Yes this is strange also, i looked at that function and seems ok. Still not linked (some of the email). 

That is why i posted above that maybe something else if not ok ? 

(i asked what is the difference of Item_url and item_link)

**Comment by eurobank** [comment]
@webmods-croatia See what is hyperlinked and what not.

![2019-08-24 13_24_23-Window](https://user-images.githubusercontent.com/4467158/63636060-f033aa80-c672-11e9-9014-1b012ca4d7ce.png)

**Comment by webmods-croatia** [comment]
I might have an idea, let me check.

**Comment by dev-101** [comment]
{ITEM_LINK} is what use in my template, it works fine. Not sure what is the problem here?

ITEM_LINK = hyperlinked URL
ITEM_URL = plain text URL

**Comment by webmods-croatia** [comment]
It seems some templates by default use {ITEM_URL} when they should use {ITEM_LINK}.

**Comment by dev-101** [comment]
Well, that can be fixed in the templates. But, for some templates that is not available.

**Comment by webmods-croatia** [comment]
What about replacing adding hyperlinks to ITEM_URL as well? That kills the purpose of it, so more a workaround than an actual fix though.

**Comment by dev-101** [comment]
Bad idea imho.

**Comment by webmods-croatia** [comment]
I guess we should just update templates SQL (if I ain't mistaken) and add hyperlinked URLs instead of plain text.

**Comment by dev-101** [comment]
Yes.
