### ISSUE TITLE
City problem with develop branch

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#39]
[20-Aug-2019 13:17:24 Europe/Madrid] PHP Notice:  Undefined index: s_city in /home/oc-includes/osclass/helpers/hDefines.php on line 521

While the above shows, the USER can't delete or edit his ad:

The listing you are trying to delete couldn't be deleted (deleting)
Sorry, we don't have any listings with that ID (editing)

BUT the admin can delete/edit it from admin dashboard, 

I _think_ this happens when the city doesn't exist in locations and the user manually enters it. Still not sure.

**Comment by webmods-croatia** [comment]
Can you test this when city exists?

**Comment by dimalif** [comment]
No the city doesn't exist, it is given by the user.

**Comment by webmods-croatia** [comment]
When user enters city, it never saves.

**Comment by webmods-croatia** [comment]
SQL error:

```
QUERY TIME 0
Error number: 1452
Error description: Cannot add or update a child row: a foreign key constraint fails (`osc-dev`.`oc_t_item_location`, CONSTRAINT `oc_t_item_location_ibfk_3` FOREIGN KEY (`fk_i_region_id`) REFERENCES `oc_t_region` (`pk_i_id`))
**************************************************
INSERT INTO oc_t_item_location (fk_i_item_id, fk_c_country_code, s_country, fk_i_region_id, s_region, fk_i_city_id, s_city, s_city_area, s_address, d_coord_lat, d_coord_long, s_zip) VALUES (7, NULL, '', '', 'testt', '', 'test', '', '', NULL, NULL, NULL)
```
