### ISSUE TITLE
SQL log doesn't work until queries.log is created

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#44]
This is a long-known issue. I don't think it was intentional. Osclass documentation says

> If Apache doesn't have write permissions, you may need to create the file first.

but oc-includes/osclass/Logger/LogDatabase.php says the following:

```php
$filename = CONTENT_PATH . 'queries.log';

if( !file_exists($filename) || !is_writable($filename) ) {
    return false;
}
```

If the file doesn't exist it will return false. Shouldn't it attempt to create it then?

**Comment by webmods-croatia** [comment]
Simple fix https://github.com/webmods-croatia/Osclass/commit/86b3ba82c28122c04ab1e43cee1abf9abc974dc9

**Comment by navjottomer** [comment]
It should, I have made a comment on your pull request, please make a new request and target develop branch.
