### ISSUE TITLE
New Feature: Built-in Osclass Renew Ads

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#50]
Would anyone consider to add a proper built-in Renew for ads ? (at some point).

**Comment by webmods-croatia** [comment]
This is a must and I would like to implement it.

**Comment by eurobank** [comment]
I don't know IF the renew could be also done via email (click a unique link).

About your question: It depends on how many times an item can be renewed.

**Comment by webmods-croatia** [comment]
Yes, that is possible.


If you want to specify renew limit, a database table (or a new column in item table) is required and that complicates stuff.


There are a lot of plugins but none of them can do it as good as a core mod does, and this is an important feature that should be available without plugins.

**Comment by dimalif** [comment]
I see no harm done for unlimited renewals, if that is simpler. 

And in future it can be expanded. I only see a problem with unlimited renew if some site is not free, has some kind of membership levels etc etc. 

Also i see a problem with premium ads  ? Still i never used them, so i don't know.

**Comment by webmods-croatia** [comment]
> I see no harm done for unlimited renewals, if that is simpler.

User can change it per their needs, I think unlimited is okay.

> And in future it can be expanded. I only see a problem with unlimited renew if some site is not free, has some kind of membership levels etc etc.

I think an on/off renew setting in admin would fix that. If someonoe has a membership plugin they can disable renew. Or mod it....

> Also i see a problem with premium ads ? Still i never used them, so i don't know.

I guess after you renew a premium ad, it should go back to regular ad?

**Comment by dimalif** [comment]
ok if you can do the Renew ON or OFF then you can also do the same for "Should the "Renew" button only update expiration date or publish date too?" ?

**Comment by webmods-croatia** [comment]
Well, yes.

**Comment by webmods-croatia** [comment]
@navjottomer your thoughts before I eventually start working?

**Comment by navjottomer** [comment]
I am currently not on features, as I said it earlier. But can be added in future.

**Comment by webmods-croatia** [comment]
> I am currently not on features, as I said it earlier. But can be added in future.

I think it would be good to make a "new features" branch where such stuff can be added.
Of course, it won't be a big priority and you could check and merge it when you have time...
