### ISSUE TITLE
change fulltext search to LIKE

### ISSUE THREAD

**Issue by mngzir** [navjottomer/Osclass#58]
Hello
I was very happy that there were at least those who wanted to develop this system and I will also help develop this system
In the new version if you can change the search type from fulltext to like
Fulltext search does not show better results

I tried very hard to improve the search type but couldn't help if you have a better solution.

Thanks

**Comment by navjottomer** [comment]
That's a very bad idea to use LIKE instead of full-text for the search queries. The issue is in Osclass's search classes, the way they are implemented is an issue and they can be improved fairly easy. 
And they will be improved in this build.
