### ISSUE TITLE
Possible cure for build-in CRON of Osclass that never works 

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#63]
Could that be a bug of Osclass, making internal CRON not to work ? If so, is the proposed solution correct ?

https://forums.osclass.org/general-help/ssl-cron-job-problem/msg170708/?boardseen#new

**Comment by navjottomer** [comment]
I think we have already fixed that, https://github.com/navjottomer/Osclass/issues/26

**Comment by dev-101** [comment]
I think that this also fixes fsockopen connection, not only curl.

**Comment by dev-101** [comment]
This can be improved a little, don't close it yet.

**Comment by dev-101** [comment]
Second part in fixed version with fsockopen can be improved to support SSL (HTTPS).

For example:

```
if (preg_match("/^https:/i", $url)) {
	$host = 'ssl://' . $host;
	$fp = @fsockopen($host, 443, $errno, $errstr, 1);
} else {
	$fp = @fsockopen($host_ssl, 80, $errno, $errstr, 1);
}
```

We extract $port variable in earlier line above ( $port = $url['port']; ), but we never use it later, but instead, 80 is hard-coded, which is contradicting (why extract it and assign in the first place? Security maybe to limit http only?).

For ssl:// to work, OpenSSL must be installed, this should be the case with most, if not all, common linux servers, not sure about IIS, tbh.

**Comment by navjottomer** [comment]
php-curl is in our minimum requirement list, so if you have the php-curl extension installed then you not need to worry about cron-job. 
But this function intends to make a quick request without waiting( not more than few milliseconds ) and this function needs improvement in that regard because current implementation ( I added the quick remedy for cron-job, my fault ) is not any better in that intent.

**Comment by dev-101** [comment]
Can you explain the delay issue? Of course, you can add manual delay of execution, but why?

**Comment by navjottomer** [comment]
> Can you explain the delay issue? Of course, you can add manual delay of execution, but why?
> To check if cron is already running?
Sorry, couldn't understand your question?

**Comment by LeonardoSilva** [comment]
Hi first of all, thanks for continuing to work on osclass. Could you tell me how to solve the cron job I have the following error.

--2019-10-08 16: 00: 01-- http://domain.com/index.php?page=cron
Resolving domain.com ... 127.0.0.1
Connecting to domain.com | 127.0.0.1 |: 80 ... connected.
HTTP request sent, awaiting response ... 301 Moved Permanently
Location: https://domain.com/index.php?page=cron [following]
--2019-10-08 16: 00: 01-- https://domain.com/index.php?page=cron

Connecting to domain.com | 127.0.0.1 |: 443 ... failed: Connection refused.
Resolving domain.com ... 127.0.0.1
Connecting to domain.com | 127.0.0.1 |: 443 ... failed: Connection refused.

I have modified the IP by 127.0.0.1 and domain.com

I am getting this error with cron hourly work

**Comment by navjottomer** [comment]
For help please visit http://forums.osclasscommunity.com/.

> Hi first of all, thanks for continuing to work on osclass. Could you tell me how to solve the cron job I have the following error.
> .....................................................
> I am getting this error with cron hourly work

**Comment by navjottomer** [comment]
Please check new changes in the commit and let me know if we can close this issue now.
64f3aa0

**Comment by navjottomer** [comment]
closing it for now.
