### ISSUE TITLE
Geo DB Offline

### ISSUE THREAD

**Issue by Tangol** [navjottomer/Osclass#65]
@navjottomer 
> Locations are fine from osclass geo DB site for now.
> We need to work on the geo DB repo to be used with this new version. BTW I have forked your https://github.com/webmods-croatia/love-osclass, I'll need to update it before we can use it in our osclass build.

Any plans to start work on an externally hosted geo script hosted on GitHub maybe, that would replace https://geo.osclass.org/newgeo.services.php ?

**Comment by dimalif** [comment]
And an other slow down of Osclass admin dashboard, if you select Locations. And along with it some warnings and notices in debug.log.

**Comment by webmods-croatia** [comment]
We had 2 ideas, still not sure which one will we use. One is to bundle location files with Osclass installer and other one is to host it on GitHub.

I was about to start working on that, but @navjottomer wasn't active for a long time now so I didn't do anything without listening to him,

**Comment by dimalif** [comment]
There is also an other problem: 

New Installations RIGHT NOW. 

How they will be able to install a country ?

**Comment by navjottomer** [comment]
It would be better to host geo data at GitHub and link our osclass build to this repo.

**Comment by webmods-croatia** [comment]
> There is also an other problem:
> 
> New Installations RIGHT NOW.
> 
> How they will be able to install a country ?

They won't be able to do it straight on install, a "no internet connection" error will show. They can import location files in admin from here https://github.com/webmods-croatia/love-osclass

**Comment by navjottomer** [comment]
related issue open already #68

**Comment by dimalif** [comment]
How can be related to 68 when 68 was opened two days later of this ?

68 is related to this.

**Comment by navjottomer** [comment]
68 has more replies so so I thought it would be better to keep the discussion on that page.
