### ISSUE TITLE
New geo database.

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#68]
@navjottomer, you said you want a GitHub repository where geo files would be stored.

I would upload the SQL files to the repo and make a JSON file with a list of all the files. Then when installing Osclass, that JSON is requested and a list of files is shown.

A similar approach should be used with locations page in admin.

Is that fine, have any suggestions?

**Comment by navjottomer** [comment]
I have already forked your love-osclass repo you can submit your changes in this repo and link it to current osclass dev build.
https://github.com/navjottomer/love-osclass

**Comment by webmods-croatia** [comment]
@navjottomer I thought we'll have a separate fork just for locations.

**Comment by dev-101** [comment]
I'd suggest to convert this repo to organization, instead of personal project.

**Comment by webmods-croatia** [comment]
Can we go talk on the [forum](https://forums.osclasscommunity.com/index.php)? I have quite a few questions and wouldn't like to spam here.

**Comment by webmods-croatia** [comment]
Anyone, anything?

**Comment by Tangol** [comment]
We are all waiting for you @webmods-croatia 🥇 !

**Comment by webmods-croatia** [comment]
> We are all waiting for you @webmods-croatia 🥇 !

I'm trying my best when I can of course. I would like some answers and thoughts then...

**Comment by dev-101** [comment]
As I said before, self-containment is the best option. Even if geo data changes between releases (not frequent or likely event), this should not affect existing or new installations. Same goes with languages, which users usually customize anyway. Less dependence = better future proof.

**Comment by webmods-croatia** [comment]
> As I said before, self-containment is the best option. Even if geo data changes between releases (not frequent or likely event), this should not affect existing or new installations. Same goes with languages, which users usually customize anyway. Less dependence = better future proof.

I'm not sure what to choose...

Self-containment - bigger file sizes, no updates, safer for future, less work.
GitHub "database" - smaller file sizes, can support updates, less safe for future, more work.

**Comment by dev-101** [comment]
Think about new users who face the issue right now. I'm not saying GitHub is going anywhere for the foreseeable future, but... that data doesn't really change much during causal updates or installation. And those who change it, they won't need overwrite for sure, at least for front-end (admin - maybe, less critical). But, even in that case, auto-update can be configured to optionally overwrite/update languages, for example.

**Comment by webmods-croatia** [comment]
We should release a Osclass 3.8.0 with removed Market and bundled location and languages.
I know that the goal of this fork is to improve Osclass and that current version if in beta phase, but we need to make something for less experienced users... 

We added this download link on osclasscommunity.com https://forums.osclasscommunity.com/Osclass_380_NoMarket.zip

**Comment by webmods-croatia** [comment]
GitHub location and language fetching could be left for future versions.

**Comment by navjottomer** [comment]
Currently, we only need locations as languages are already included in osclass dev build. I have updated the JSON list in https://github.com/navjottomer/Osclass-Extras/tree/master/locations

After this is done, the only thing remaining is to test all functionality and release the first stable build from this repository.

**Comment by webmods-croatia** [comment]
Okay. Then I'll work on integrating JSON locations. I will make a pull
request to modify that file a bit.

čet, 3. lis 2019. 18:59 Navjot Tomer <notifications@github.com> je napisao:

**Comment by navjottomer** [comment]
Thanks, @webmods-croatia you can also modify a little script dir2json.py which will make this process easier.

**Comment by webmods-croatia** [comment]
Just a small update, I started working recently, all going well. :)

**Comment by webmods-croatia** [comment]
Location import on install finished. Now working on the location page in admin.

**Comment by Tangol** [comment]
> Location import on install finished. Now working on the location page in admin.
> 
> I'll make a pull request when I will be able to change URL's from my repo to Navjot's one (waiting to merge list.json change).
> 
Any news on this?

**Comment by webmods-croatia** [comment]
@Tangol I've been busy so I didn't work on this lately...

@navjottomer Can you merge https://github.com/navjottomer/Osclass-Extras/pull/1?

**Comment by navjottomer** [comment]
Merged.

**Comment by webmods-croatia** [comment]
Where should I store the GitHub URL? I don't think it's a good idea to hardcode them in installer and location page.

**Comment by navjottomer** [comment]
For now I think it's safe to use current GitHub repo. We need more work before we copy all this api stuff to a dedicated self hosted system.

**Comment by Tangol** [comment]
> Where should I store the GitHub URL? I don't think it's a good idea to hardcode them in installer and location page.

Actually being an essential part of Osclass, I think it would be best to hardcode the url as it's safe to say that GitHub won't go anywhere anytime soon.

**Comment by webmods-croatia** [comment]
I will do the final tests today and then submit a pull request. Sorry for being so slow with this, but I've been busy and had quite a few problems with my PC.

**Comment by webmods-croatia** [comment]
https://github.com/navjottomer/Osclass/pull/75

**Comment by navjottomer** [comment]
Please check and let me know, so we can close this issue.

**Comment by webmods-croatia** [comment]
It can be closed. PR is merged. If there will be bugs related to this new issues can be opened.
