### ISSUE TITLE
Need help on maintaining Wiki 

### ISSUE THREAD

**Issue by navjottomer** [navjottomer/Osclass#69]
Currently, we do not have any documentation left for osclass, It would be better if people who are not developers can help us to maintain https://github.com/navjottomer/Osclass/wiki 
https://github.com/navjottomer/Osclass/tree/gh-pages

**Comment by mkraha** [comment]
@navjottomer Will you interested to move everything under @osclasscommunity. I promise100% for osclass, No ads or paid things.

**Comment by navjottomer** [comment]
You can fork it, if you want, that is why it's on GitHub. I don't understand why it needs moving.

**Comment by mkraha** [comment]
> 
> 
> You can fork it, if you want, that is why it's on GitHub. I don't understand why it needs moving.

I think we keep everything  under name of community not one personal or person. You will be owner rist owner of it. Here, what i am trying is to make united community for osclass with all who loves and want to contribute.

**Comment by navjottomer** [comment]
Sorry, I think you didn't understand, this is an open repo. If you or anybody else think that they need their own repo can fork it to their own use. 
There is no point of discussion on this topic cause everyone knows how GitHub works.

**Comment by mkraha** [comment]
@navjottomer Thanks. i will delete comments here.

**Comment by navjottomer** [comment]
New repo for Documentation https://github.com/navjottomer/Osclass-Docs
