### ISSUE TITLE
[QUESTION] The Future of this ?

### ISSUE THREAD

**Issue by eurobank** [navjottomer/Osclass#7]
Hi,
Do you have any idea how your work will continue ? I mean i see 3.7.5 RC also here synced etc etc but will your work be released ever ?

What are the plans ?

**Comment by navjottomer** [comment]
After much thought current plan is to create seprate osclass build with extra features but directly compatible with original osclass ecosystem.
Currently working on integrating libraries through composer.

**Comment by eurobank** [comment]
Got it !!

Thanks.
