### ISSUE TITLE
777 permissions in utils.php

### ISSUE THREAD

**Issue by dimalif** [navjottomer/Osclass#71]
Checking the commits, i see several 777 permissions in utils.php. I do remember that some have been fixed in 3.8 stock a year ago or so.

I think no 777 should be used. 755 is enough. Maybe those also should be fixed.

**Comment by navjottomer** [comment]
I fixed it in my repo before 3.8 was released but fetching from it replaced my modified utilis.php. 
In a stock 3.8 utils.php file, not all places were fixed.

**Comment by dimalif** [comment]
Doing a quick search for all "0777" in php files, i see it also exists in several other places apart from utils.php.

**Comment by navjottomer** [comment]
Please make a pull request and I'll merge it after review.

**Comment by dimalif** [comment]
I would make a pull request if a knew to code and about all that.

The mode "0777" exist in:

C:\Users\admin\Desktop\Osclass-develop\oc-includes\Vendor\Ezyang\htmlpurifier\Library\HTMLPurifier\DefinitionCache\Serializer.php 

C:\Users\admin\Desktop\Osclass-develop\oc-includes\Vendor\Pclzip\Pclzip\pclzip.lib.php 

C:\Users\admin\Desktop\Osclass-develop\oc-includes\Vendor\phpseclib\phpseclib\phpseclib\Net\Sftp.php

**Comment by navjottomer** [comment]
Sorry,  files you mentioned are in third party libraries.

**Comment by dimalif** [comment]
ok, you know about all this. So we are good.
