### ISSUE TITLE
an item is displayed several times in an alert

### ISSUE THREAD

**Issue by hilbertus** [navjottomer/Osclass#79]
If you have anonymous items and registered users, it can happen that the stored alerts display the same ad several times.

**Comment by navjottomer** [comment]
Waiting for a new pull request.

**Comment by dev-101** [comment]
This is related to #1832 and there was another error reported here: https://github.com/osclass/Osclass/commit/734c89588edbb15d58abbc9b1eb57e6b35b36210

I wonder if this can be fixed, or should we revert the changes and use old version?

**Comment by navjottomer** [comment]
We may need more time on this issue to properly fix it or to have better solution. I am holding the pull request for now
