### ISSUE TITLE
Text overflow due to missing word break

### ISSUE THREAD

**Issue by krakster** [navjottomer/Osclass#81]
**Describe the bug**
Hey guys, I'm hitting the same bug u/marius-ciclistu had on Osclass forums, tried something along the lines of his/her solution and it worked for me.

The bug is described [here](http://webcache.googleusercontent.com/search?q=cache:uMjAGjAxpTIJ:https://forums.osclass.org/development/item-description-ltpgt-tag-with-word-wrapbreak-word-word-breakbreak-word/&client=firefox-b-d&hl=en&gl=es&strip=1&vwsrc=0)

Perhaps this is already fixed but I'm posting here just in case.

**To Reproduce**
1. Create a new add with a long word, in my site it happens when people try to format ads like if were an ASCII doc  

```
############################# (i.e. longer than mobile page width)
Shoes
one
two
three

#####################
Hoodies
one
two
```

2. Open the site on mobile
3. See error on the page the ad is listed

**Expected behavior**
The text should break.

**Screenshots**
![Screen Shot 2019-10-29 at 08 48 38](https://user-images.githubusercontent.com/16103263/67747490-1c7bf680-fa29-11e9-8e12-21db9e7a68b9.png)
![Screen Shot 2019-10-29 at 08 48 58](https://user-images.githubusercontent.com/16103263/67747496-20a81400-fa29-11e9-9cff-e35ee78613a4.png)
![Screen Shot 2019-10-29 at 08 48 52](https://user-images.githubusercontent.com/16103263/67747816-decb9d80-fa29-11e9-9cf5-89aba9faf004.png)

![Screen Shot 2019-10-29 at 08 49 02](https://user-images.githubusercontent.com/16103263/67747503-23a30480-fa29-11e9-8676-8e85000fb000.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox, Chromium
 - Version 70, 76

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI 9T
 - OS: Android 9
 - Browser Brave, Firefox
 - Version 1.4.2, 68.3

**Solution**

This is what worked for me:

Adding the following to `oc-content/themes/bender/css/main.css`

```
div#main div#item-content div#description p,.listing-card {
    overflow-wrap:break-word;
    word-break: break-word;
}
```

**Comment by navjottomer** [comment]
Not related to osclass itself, it's a bender theme bug.
