### ISSUE TITLE
Removal of legacy links in different place in osclass.

### ISSUE THREAD

**Issue by navjottomer** [navjottomer/Osclass#84]
**Describe the bug**
Remove Readme, Feedback, Forums link from the installer and other legacy links from admin theme. They confuse new users and not needed.

**Comment by webmods-croatia** [comment]
@navjottomer Can I include this in the next location import-related PR?

**Comment by navjottomer** [comment]
@webmods-croatia you can make a new pr for this issue, just remember work on release branch not on develop branch.

**Comment by navjottomer** [comment]
I hope it is fixed.
@eurobank

**Comment by eurobank** [comment]
@navjottomer 

I will have to check tomorrow to be sure. I will update asap.

**Comment by eurobank** [comment]
@navjottomer Works great now. No freeze no slowdown.
