### ISSUE TITLE
US couldn't be installed on localhost during location stage.

### ISSUE THREAD

**Issue by navjottomer** [navjottomer/Osclass#85]
**Describe the bug**
For more details:
https://github.com/navjottomer/Osclass/issues/83#issuecomment-548334258
Related #83

**Comment by navjottomer** [comment]
@webmods-croatia Please check if possible.

**Comment by webmods-croatia** [comment]
@navjottomer @dev-101 I'll look into it ASAP. I've had no problems with few countries but didn't test US. Maybe it's due to max_execution_time or smth.

**Comment by webmods-croatia** [comment]
@navjottomer I'm trying to test on localhost and I somehow get "No internet connection. You can continue the installation and insert countries later.".  Seems like osc_file_get_contents isn't working in my case, for some reason.

**Comment by webmods-croatia** [comment]
PHP Warning:  file_get_contents(https://raw.githubusercontent.com/webmods-croatia/love-osclass/master/locations/US-United States.sql): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

Could it be the space in the name?

**Comment by webmods-croatia** [comment]
@navjottomer @dev-101 It's because of the space in the file name.
