### ISSUE TITLE
osc_has_static_pages  

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#92]
**Describe the bug**
 osc_has_static_pages  extract all  db fields ,  description multilanguage too (  some  kb or even mb ) and description  is never used  (theme footer  is  the only call ) 

```php 
<?php
        osc_reset_static_pages();
        while( osc_has_static_pages() ) { ?>
            <li>
                <a href="<?php echo osc_static_page_url(); ?>"><?php echo osc_static_page_title(); ?></a>
            </li>
        <?php
        }
        ?>
```

 we need to add a new method in Page  to extract only the url and  title to display in footer ..
ps: i've implemented cache to avoid some db calls ..

**Comment by eurobank** [comment]
Descriptions exist in Osclass but some are never used. Categories/subcategories for example.

**Comment by web-media** [comment]
#182   created . 
@navjottomer .. check the code pls
