### ISSUE TITLE
Item extendData

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#98]
public function extendData($items)
Extends the given array $items with description in available locales

Duplicate the amount of db  queries to find all available locales , but in 99.99  use case displays only one description  based on user current locale even the site is multilang .
For the search page where speed matter we should  not extendData for items and search for user current locale   item description only 
 Beside item post/edit i can't see any good usage of  extending data with all available locales.
Can anyone provide some scenario where  extend data with all locales is really needed ? 
![Capture](https://user-images.githubusercontent.com/5124319/68248643-88f48800-001d-11ea-813d-b139c04e976b.PNG) 
ps: ia have few  items in  test db that's why  db query so fast

**Comment by navjottomer** [comment]
Editing Item, btw 90% installation stick to a single language or two. Even if all languages are enabled they rarely get populated with content. 
What we can do is stick to current default behaviour and add a new method to restrict loading everything, this will avoid compatibility issue.
